language: php
php:
    - 5.4

script: VERBOSE=true ./run-tests.sh

before_script:
    # install composer
    - composer install --no-interaction --prefer-source

    - cd tests
    - mkdir -m 777 temp